# Use Node.js LTS version as base image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install --production
# Copy application code
COPY . .

# Expose the port the app runs on
EXPOSE 5000

# # Set environment to production
# ENV NODE_ENV=production

# Start the application
CMD ["node", "index.js"]
